[package]
name = "desktop_file_parser"
version = "0.1.0"
edition = "2021"
authors = ["David Huang jiguangllsw@gmail.com"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/BL-CZY/desktop_file_parser"
documentation = "https://github.com/BL-CZY/desktop_file_parser?tab=readme-ov-file#freedesktop-desktop-entry-parser"

[dependencies]
freedesktop-icons = "0.2.6"
thiserror = "2.0.7"
